import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
// Note: firebase_options.dart is generated by FlutterFire CLI: flutterfire configure
// If you already have firebase_options.dart in your lib folder, uncomment the import:
// import '../firebase_options.dart';

class FirebaseService {
  static Future<void> initialize() async {
    try {
      // If DefaultFirebaseOptions is present in your project:
      // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
      await Firebase.initializeApp();
      debugPrint('[FirebaseService] Firebase initialized successfully.');
    } catch (e) {
      debugPrint('[FirebaseService] Error during Firebase initialization: $e');
      rethrow;
    }
  }
}
