buildscript {
    ext.kotlin_version = '1.9.22'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // Google Services Gradle plugin for Firebase & Google Sign-In
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
    afterEvaluate { project ->
        project.tasks.matching { it.name.toLowerCase().contains("kotlin") }.configureEach {
            try {
                incremental = false
            } catch (Exception ignored) {}
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
